version: '3.7'
services:
  interlink:
    image:  docker.io/surax98/interlink:latest
    restart: always
    network_mode: "host"
    volumes:
    - type: bind
      source: ./kustomizations
      target: /etc/interlink
    # healthcheck:
    #   test: ["CMD", "/check.sh"]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 5s
  docker-sidecar:
    image: docker.io/surax98/docker-sidecar:latest
    restart: always
    privileged: true
    network_mode: "host"
    volumes:
    - type: bind
      source: ./kustomizations
      target: /etc/interlink
    # healthcheck:
    #   test: ["CMD", "/check.sh"]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 5s
  vk:
    image: docker.io/surax98/vk:latest
    restart: always
    privileged: true
    network_mode: "host"
    volumes:
    - type: bind
      source: ./kustomizations
      target: /etc/interlink
    environment:
      - INTERLINKCONFIGPATH=/etc/interlink/InterLinkConfig.yaml
      - VKTOKENFILE=/etc/interlink/dummy_token
      - TOKEN_PATH=/etc/interlink/dummy_token
      - KUBECONFIG=/etc/interlink/kubeconfig.yaml
      - CONFIGPATH=/etc/interlink/knoc-cfg.json
      - NODENAME=test-vk 
    # healthcheck:
    #   test: ["CMD", "/check.sh"]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 5s