version: '3.7'
services:
  interlink:
    build:
      context: ../../../
      dockerfile: docker/Dockerfile.interlink
    restart: always
    network_mode: "host"
    volumes:
    - type: bind
      source: ../../../cmd/sidecars/htcondor/
      target: /etc/interlink
    environment:
    - INTERLINKCONFIGPATH=/etc/interlink/InterLinkConfig.yaml
    - KUBECONFIG=/etc/interlink/kubeconfig.yaml
    # healthcheck:
    #   test: ["CMD", "/check.sh"]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 5s
  docker-sidecar:
    build:
      context: ../../../
      dockerfile: docker/htcondor/Dockerfile
    restart: always
    privileged: true
    cap_add:
    - SYS_ADMIN
    network_mode: "host"
    volumes:
    - type: bind
      source: ../../../cmd/sidecars/htcondor/
      target: /utils
    # healthcheck:
    #   test: ["CMD", "/check.sh"]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 5s
